title: UW Global Innovation Exchange MarCom
description: A compilation of the most-used marketing assets for internal use at the Global Innovation Exchange
theme: just-the-docs

url: https://gixmarketing.github.io/MarCom

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
